from django.urls import path
from busticket import views

urlpatterns = [
    path('', views.index, name='index'),
    path('bus/',views.bus),  
    path('busnew/',views.busnew),  
    path('busedit/<int:id>', views.busedit),  
    path('busupdate/<int:id>', views.busupdate),  
    path('busdelete/<int:id>', views.busdelete),  
    path('driver/',views.driver),  
    path('drivernew/',views.drivernew),  
    path('driveredit/<int:id>', views.driveredit),  
    path('driverupdate/<int:id>', views.driverupdate),  
    path('driverdelete/<int:id>', views.driverdelete), 
    path('trip/',views.get_list_of_trips),  
    path('tripnew/',views.add_new_trip),  
    path('tripedit/<int:id>', views.tripedit),  
    path('tripupdate/<int:id>', views.update_trip_details),  
    path('tripdelete/<int:id>', views.delete_trip), 
    path('searchtrip/',views.search_trip),
    path('search/',views.search),
    path('reservation/',views.reservation),
    path('reservationnew/<int:id>',views.reservationnew),
    path('reservationedit/<int:id>',views.reservationedit),
    path('reservationupdate/<int:id>',views.reservationupdate),
    path('reservationdelete/<int:id>', views.reservationdelete), 
    path('openpurchasepage/<int:id>', views.openpurchasepage, name="openpurchasepage"),
    path('ticket/',views.ticket),
    path('register/',views.register),
    path('checkout/<int:id>', views.checkout), 
    path('thanks/<int:id>', views.thanks, name="thanks"), 
]
