# Generated by Django 2.2 on 2021-04-24 18:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Driver', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_name',
        ),
        migrations.AddField(
            model_name='bus',
            name='brand_name',
            field=models.CharField(default='Mercedes Benz', max_length=30),
        ),
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_no',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busticket.Driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_city', to='busticket.City'),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_city', to='busticket.City'),
        ),
    ]
