# Generated by Django 2.2 on 2021-05-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0004_auto_20210430_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat_count',
            field=models.IntegerField(default=52),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busticket.BusCompany'),
        ),
    ]
