# Generated by Django 2.2 on 2021-05-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0006_auto_20210509_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_no',
            field=models.UUIDField(default='bb923402', unique=True),
        ),
    ]
