# Generated by Django 2.2 on 2021-05-09 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0007_auto_20210509_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_no',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
