# Generated by Django 2.2 on 2021-05-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0008_auto_20210509_2239'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='unique trip',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busticket.Passenger'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='busticket.Trip'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('bus', 'from_city', 'to_city'), name='unique trip'),
        ),
    ]
