# Generated by Django 2.2 on 2021-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0011_transaction_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_no',
        ),
    ]
