# Generated by Django 2.2 on 2021-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0012_remove_trip_trip_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(default='Default Passenger', max_length=30),
        ),
    ]
