# Generated by Django 2.2 on 2021-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0013_auto_20210529_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscompany',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='buscompany',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='buscompany',
            name='tel_no',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='buscompany',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
