# Generated by Django 2.2 on 2021-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busticket', '0014_auto_20210613_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompany',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
